	class CfgWorlds
	{
		class GenericNames
		{
			class PB_BelgianMen
			{
				class FirstNames 
				{
				Aaron = "Aaron";
				Abel = "Abel";
				Achille = "Achille";
				Adam = "Adam";
				Aiden = "Aiden";
				Alessio = "Alessio";
				Alex = "Alex";
				Alexander = "Alexander";
				Alexandre = "Alexandre";
				Alexis = "Alexis";
				Ali = "Ali";
				Amir = "Amir";
				Anas = "Anas";
				Andrea = "Andrea";
				Andreas = "Andreas";
				Antoine = "Antoine";
				Arthur = "Arthur";
				Aster = "Aster";
				August = "August";
				Auguste = "Auguste";
				Augustin = "Augustin";
				Axel = "Axel";
				Ayaz = "Ayaz";
				Ayden = "Ayden";
				Ayoub = "Ayoub";
				Baptiste = "Baptiste";
				Bas = "Bas";
				Basile = "Basile";
				Bilal = "Bilal";
				Cas = "Cas";
				César = "César";
				Charles = "Charles";
				Charlie = "Charlie";
				Charly = "Charly";
				Clément = "Clément";
				Côme = "Côme";
				Cyriel = "Cyriel";
				Daan = "Daan";
				Daniel = "Daniel";
				David = "David";
				Diego = "Diego";
				Dré = "Dré";
				Eden = "Eden";
				Elias = "Elias";
				Eliott = "Eliott";
				Elliot = "Elliot";
				Emiel = "Emiel";
				Emil = "Emil";
				Émile = "Émile";
				Emile = "Emile";
				Emilio = "Emilio";
				Emir = "Emir";
				Enzo = "Enzo";
				Ethan = "Ethan";
				Ezio = "Ezio";
				Ezra = "Ezra";
				Félix = "Félix";
				Felix  = "Felix ";
				Ferre = "Ferre";
				Finn = "Finn";
				Flor = "Flor";
				Floris = "Floris";
				Fons = "Fons";
				Gabin = "Gabin";
				Gabriël = "Gabriël";
				Gabriel = "Gabriel";
				Gaspard = "Gaspard";
				Gaston = "Gaston";
				George = "George";
				Georges = "Georges";
				Gust = "Gust";
				Hamza = "Hamza";
				Haroun = "Haroun";
				Hector = "Hector";
				Henri = "Henri";
				Hugo = "Hugo";
				Idris = "Idris";
				Isaac = "Isaac";
				Issa = "Issa";
				Jack = "Jack";
				James = "James";
				Jayden  = "Jayden ";
				Jean = "Jean";
				Jef = "Jef";
				Jules = "Jules";
				Julian = "Julian";
				Julien = "Julien";
				Kaïs = "Kaïs";
				Kamiel = "Kamiel";
				Kasper = "Kasper";
				Kobe = "Kobe";
				Lars = "Lars";
				Lenn = "Lenn";
				Leo = "Leo";
				Léo  = "Léo ";
				Leon = "Leon";
				Léon = "Léon";
				Levi = "Levi";
				Lewis = "Lewis";
				Liam = "Liam";
				Lias = "Lias";
				Lino = "Lino";
				Lio = "Lio";
				Livio = "Livio";
				Loïc = "Loïc";
				Lorenzo = "Lorenzo";
				Lou = "Lou";
				Louis = "Louis";
				Lowie = "Lowie";
				Luca = "Luca";
				Lucas = "Lucas";
				Lucien = "Lucien";
				Luka = "Luka";
				Lukas = "Lukas";
				Lyam = "Lyam";
				Maël = "Maël";
				Marcel = "Marcel";
				Marius = "Marius";
				Martin = "Martin";
				Mason = "Mason";
				Mateo = "Mateo";
				Mathéo = "Mathéo";
				Mathias = "Mathias";
				Mathieu = "Mathieu";
				Mathis = "Mathis";
				Mathys = "Mathys";
				Mats = "Mats";
				Matteo = "Matteo";
				Mattia = "Mattia";
				Maurice = "Maurice";
				Mauro = "Mauro";
				Max = "Max";
				Maxence = "Maxence";
				Maxim = "Maxim";
				Maxime = "Maxime";
				Miel = "Miel";
				Mil = "Mil";
				Milan = "Milan";
				Milo = "Milo";
				Morris = "Morris";
				Moussa = "Moussa";
				Naël = "Naël";
				Nathan = "Nathan";
				Nicolas = "Nicolas";
				Nino = "Nino";
				Noa = "Noa";
				Noah = "Noah";
				Noé = "Noé";
				Nolan = "Nolan";
				Oliver = "Oliver";
				Omar = "Omar";
				Oscar = "Oscar";
				Oskar = "Oskar";
				Otis = "Otis";
				Owen = "Owen";
				Paul = "Paul";
				Raphaël = "Raphaël";
				Rayan = "Rayan";
				Remi = "Remi";
				Robin = "Robin";
				Romain = "Romain";
				Roméo = "Roméo";
				Sacha = "Sacha";
				Sam = "Sam";
				Samuel = "Samuel";
				Sem = "Sem";
				Simon = "Simon";
				Stan = "Stan";
				Theo = "Theo";
				Théo = "Théo";
				Thiago = "Thiago";
				Thomas = "Thomas";
				Tiago = "Tiago";
				Timéo = "Timéo";
				Tom = "Tom";
				Tuur = "Tuur";
				Valentin = "Valentin";
				Vic = "Vic";
				Victor = "Victor";
				Vik = "Vik";
				Viktor = "Viktor";
				Vince = "Vince";
				Warre = "Warre";
				William = "William";
				Wout = "Wout";
				Yahya = "Yahya";
				Yanis = "Yanis";
				Younes = "Younes";
				Zayd = "Zayd";
			};
			class LastNames 
			{
				Baert = "Baert"
				Bauchau = "Bauchau"
				Bauwens = "Bauwens"
				Berckmans = "Berckmans"
				Bogaert = "Bogaert"
				Borremans = "Borremans"
				Bosmans = "Bosmans"
				Bossuyt = "Bossuyt"
				Breydel = "Breydel"
				Breyne = "Breyne"
				Broekx = "Broekx"
				Cammaerts = "Cammaerts"
				CartondeWiart = "Carton de Wiart"
				Ceulemans = "Ceulemans"
				Christiaens = "Christiaens"
				Claerhout = "Claerhout"
				Claes = "Claes"
				Claeys = "Claeys"
				Clijsters = "Clijsters"
				Cools = "Cools"
				Coomans = "Coomans"
				Coosemans = "Coosemans"
				Courtois = "Courtois"
				Cronje = "Cronje"
				D'Hondt = "D'Hondt"
				Daems = "Daems"
				Danneels = "Danneels"
				DeBacker = "De Backer"
				DeBever = "De Bever"
				DeCaluwé = "De Caluwé"
				DeClerck = "De Clerck"
				DeClercq = "De Clercq"
				DeCoster = "De Coster"
				DeCroo = "De Croo"
				DeFauw = "De Fauw"
				DeGroote = "De Groote"
				DeHondt = "De Hondt"
				DeKeyser = "De Keyser"
				DeSmedt = "De Smedt"
				DeSmet = "De Smet"
				DeVos = "De Vos"
				DeVreese = "De Vreese"
				DeVriese = "De Vriese"
				DeWitte = "De Witte"
				Declercq = "Declercq"
				Deconinck = "Deconinck"
				Defaux = "Defaux"
				Dejonckheere = "Dejonckheere"
				Delmotte = "Delmotte"
				Demol = "Demol"
				Desmet = "Desmet"
				Devos = "Devos"
				Dhondt = "Dhondt"
				Dhont = "Dhont"
				Dierckx = "Dierckx"
				Dierickx = "Dierickx"
				Dievoet = "Dievoet"
				Dievoort = "Dievoort"
				Dirickx = "Dirickx"
				Dufaux = "Dufaux"
				Duits = "Duits"
				Dupont = "Dupont"
				Faux = "Faux"
				Feyaerts = "Feyaerts"
				Fourier = "Fourier"
				Franchoys = "Franchoys"
				Fribourg = "Fribourg"
				Gevaert = "Gevaert"
				Geybels = "Geybels"
				Goeminne = "Goeminne"
				Goethals = "Goethals"
				Goffin = "Goffin"
				Goossens = "Goossens"
				Goris = "Goris"
				Hayez = "Hayez"
				Hemelsoet = "Hemelsoet"
				Henderickx = "Henderickx"
				Hendrickx = "Hendrickx"
				Hendrikx = "Hendrikx"
				Heylen = "Heylen"
				Heymans = "Heymans"
				Huyghebaert = "Huyghebaert"
				Jorissen = "Jorissen"
				Jouret = "Jouret"
				Kickx = "Kickx"
				Laisné = "Laisné"
				Lambert = "Lambert"
				Lauwers = "Lauwers"
				Legot = "Legot"
				Lenaerts = "Lenaerts"
				Leunis = "Leunis"
				Lievens = "Lievens"
				Lilar = "Lilar"
				Louwagie = "Louwagie"
				Lybaert = "Lybaert"
				Maes = "Maes"
				Meerschaert = "Meerschaert"
				Mertens = "Mertens"
				Meyers = "Meyers"
				Michiels = "Michiels"
				Naessens = "Naessens"
				Neefs = "Neefs"
				Omloop = "Omloop"
				Ouwerx = "Ouwerx"
				Peeters = "Peeters"
				Pinxten = "Pinxten"
				Poels = "Poels"
				Provoost = "Provoost"
				Putzeys = "Putzeys"
				Raes = "Raes"
				Rampelberg = "Rampelberg"
				Rooman = "Rooman"
				Serruys = "Serruys"
				Smet = "Smet"
				Smets = "Smets"
				Stevens = "Stevens"
				Taelman = "Taelman"
				Taminiaux = "Taminiaux"
				Theys = "Theys"
				Thys = "Thys"
				VanAcker = "Van Acker"
				VanBaer = "Van Baer"
				VanBelleghem = "Van Belleghem"
				VanDaele = "Van Daele"
				VanDamme = "Van Damme"
				VandeVijver = "Van de Vijver"
				VandeWalle = "Van de Walle"
				VandeWiele = "Van de Wiele"
				VandenAbeele = "Van den Abeele"
				VanDenBerghe = "Van Den Berghe"
				VandenBossche = "Van den Bossche"
				VandenBroeck = "Van den Broeck"
				VanderElst = "Van der Elst"
				VanDerVeken = "Van Der Veken"
				VanDyck = "Van Dyck"
				VanHecke = "Van Hecke"
				VanHove = "Van Hove"
				VanTomme = "Van Tomme"
				VanVolxem = "Van Volxem"
				Vandamme = "Vandamme"
				Vandenbroucke = "Vandenbroucke"
				Vanderaerden = "Vanderaerden"
				Vanderbeken = "Vanderbeken"
				Vandorme = "Vandorme"
				Vanendert = "Vanendert"
				Vanhoutte = "Vanhoutte"
				Vanthourenhout = "Vanthourenhout"
				Verbauwen = "Verbauwen"
				Verbeke = "Verbeke"
				Vercheval = "Vercheval"
				Vercruysse = "Vercruysse"
				Verhaegen = "Verhaegen"
				Verhaeghe = "Verhaeghe"
				Verhaert = "Verhaert"
				Verhavert = "Verhavert"
				Vermeersch = "Vermeersch"
				Vermeiren = "Vermeiren"
				Vermeulen = "Vermeulen"
				Verschaeve = "Verschaeve"
				Verschuere = "Verschuere"
				Verschueren = "Verschueren"
				Verstraete = "Verstraete"
				Vervliet = "Vervliet"
				Vizard = "Vizard"
				Vleminckx = "Vleminckx"
				Vyncke = "Vyncke"
				Wathelet = "Wathelet"
				Wauters = "Wauters"
				Werbrouck = "Werbrouck"
				Wesmael = "Wesmael"
				Willems = "Willems"
				Wouters = "Wouters"
				Wuyts = "Wuyts"
				Xhonneux = "Xhonneux"
				Ykens = "Ykens"
			};
		};	
	};
};